In [1]:
import pandas as pd

In [10]:
print(pd.__version__)

3.0.3

In [16]:
download_url = "https://httpbin.org/get"

In [17]:
import requests

In [18]:
response = requests.get(download_url)

In [19]:
print(response.status_code)

200

In [20]:
with open("main_ucl.csv", "wb") as f:
    f.write(response.content)

In [24]:
!dir

ExplorePandas.ipynb
config.yaml
csv_processing.py
data.csv
data.py
employee_birthday.csv
fifa_world_cup_2026_player_performance.csv
fifa_world_cup_2026_player_performance.csv:Zone.Identifier
file.log
hello_frieda.json
hello_frieda.py
hrdata.csv
logger.conf
main_ucl.csv
main_ucl.csv:Zone.Identifier
mini_frieda.json
python_logging.py
python_logging_dict.py
read_csv.ipynb
sample_plate_input.csv:Zone.Identifier
wikipedia.ipynb
world_population.csv

In [27]:
  df = pd.read_csv("fifa_world_cup_2026_player_performance.csv")

In [28]:
type(df)

pandas.DataFrame

In [29]:
len(df)

54600

In [30]:
df.shape

(54600, 75)

In [32]:
df.head()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

In [34]:
pd.set_option("display.max.colum", None)
pd.set_option('display.precision', 2)

In [35]:
df.tail()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,club_name,market_value_eur,match_id,match_date,stadium,city,opponent_team,tournament_stage,match_result,goals_team,goals_opponent,minutes_played,goals,assists,shots,shots_on_target,expected_goals_xg,expected_assists_xa,key_passes,successful_passes,total_passes,pass_accuracy,dribbles_attempted,successful_dribbles,crosses,successful_crosses,tackles,interceptions,clearances,blocks,aerial_duels_won,aerial_duels_lost,recoveries,defensive_actions,fouls_committed,fouls_suffered,yellow_cards,red_cards,offsides,saves,save_percentage,punches,clean_sheet,goals_conceded,penalty_saves,distance_covered_km,sprint_distance_km,top_speed_kmh,accelerations,decelerations,stamina_score,player_rating,performance_score,offensive_contribution,defensive_contribution,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,Pohang Steelers,2038987,M01050,2026-07-24,Estadio BBVA,Monterrey,Senegal,Final,W,1,0,0,0,0,0,0,0.0,0.0,0,0,0,0.86,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0.0,0.0,0.0,0,0,62.9,0.0,0.0,18.9,40.2,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,Bunyodkor,18303109,M01050,2026-07-24,Estadio BBVA,Monterrey,Senegal,Final,W,1,0,0,0,0,0,0,0.0,0.0,0,0,0,0.77,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0.0,0.0,0.0,0,0,79.5,0.0,3.1,28.8,37.6,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,Al-Duhail,9162130,M01050,2026-07-24,Estadio BBVA,Monterrey,Senegal,Final,W,1,0,0,0,0,0,0,0.0,0.0,0,0,0,0.85,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0.0,0.0,0.0,0,0,69.7,0.0,2.2,64.8,59.0,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,Kawasaki Frontale,47033556,M01050,2026-07-24,Estadio BBVA,Monterrey,Senegal,Final,W,1,0,0,0,0,0,0,0.0,0.0,0,0,0,0.74,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0.0,0.0,0.0,0,0,67.8,0.0,2.4,14.5,99.0,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,Ulsan HD,39256189,M01050,2026-07-24,Estadio BBVA,Monterrey,Senegal,Final,W,1,0,0,0,0,0,0,0.0,0.0,0,0,0,0.81,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0.0,0.0,0.0,0,0,81.4,0.0,0.0,11.4,99.0,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

In [36]:
df.describe()

,age,jersey_number,height_cm,weight_kg,market_value_eur,goals_team,goals_opponent,minutes_played,goals,assists,shots,shots_on_target,expected_goals_xg,expected_assists_xa,key_passes,successful_passes,total_passes,pass_accuracy,dribbles_attempted,successful_dribbles,crosses,successful_crosses,tackles,interceptions,clearances,blocks,aerial_duels_won,aerial_duels_lost,recoveries,defensive_actions,fouls_committed,fouls_suffered,yellow_cards,red_cards,offsides,saves,save_percentage,punches,clean_sheet,goals_conceded,penalty_saves,distance_covered_km,sprint_distance_km,top_speed_kmh,accelerations,decelerations,stamina_score,player_rating,performance_score,offensive_contribution,defensive_contribution,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
count,54600.00,54600.0,54600.00,54600.00,5.46e+04,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.0,5.46e+04,54600.00,54600.00,54600.00,54600.00,5.46e+04,54600.00,5.46e+04,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00,54600.00
mean,26.30,13.5,181.65,75.75,2.01e+07,1.33,1.33,36.20,0.06,0.05,0.45,0.05,0.02,0.02,0.47,15.47,19.18,0.81,0.60,0.16,0.45,0.02,0.80,0.63,0.81,0.23,0.75,0.36,1.39,2.47,0.42,0.32,0.1,5.60e-03,0.09,0.12,0.03,0.03,9.18e-03,0.05,3.33e-03,4.00,0.46,18.65,10.04,8.85,81.89,3.63,36.83,44.72,52.73,2.85,60.32,46.14,63.75,55.57,0.64,0.61,272.30,0.03,3.63
std,4.07,7.5,6.28,3.95,2.72e+07,1.15,1.15,36.42,0.25,0.24,0.95,0.24,0.07,0.07,0.94,18.75,22.62,0.07,1.15,0.50,0.86,0.14,1.34,1.13,1.53,0.56,1.17,0.71,2.02,3.64,0.77,0.65,0.3,7.47e-02,0.32,0.70,0.14,0.21,9.54e-02,0.33,5.76e-02,4.02,0.48,16.02,10.58,9.39,10.77,3.16,31.07,24.87,23.90,4.23,20.23,22.42,19.86,13.66,1.09,0.93,116.81,0.21,3.16
min,17.00,1.0,163.00,65.00,5.29e+05,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.42,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00e+00,0.00,0.00,0.00,0.00,0.00e+00,0.00,0.00e+00,0.00,0.00,0.00,0.00,0.00,50.00,0.00,0.00,1.00,5.00,0.00,15.00,5.00,25.00,15.00,0.00,0.00,0.00,0.00,0.00
25%,23.00,7.0,177.00,73.00,4.44e+06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.76,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00e+00,0.00,0.00,0.00,0.00,0.00e+00,0.00,0.00e+00,0.00,0.00,0.00,0.00,0.00,74.60,0.00,0.70,25.68,33.10,0.00,43.70,29.80,46.50,46.40,0.00,0.00,184.00,0.00,0.00
50%,26.00,13.5,182.00,76.00,1.03e+07,1.00,1.00,24.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,9.00,11.00,0.82,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00e+00,0.00,0.00,0.00,0.00,0.00e+00,0.00,0.00e+00,3.00,0.30,29.90,6.00,6.00,82.60,5.50,54.10,41.60,49.90,1.10,57.00,40.50,61.10,55.00,0.00,0.00,268.00,0.00,5.40
75%,29.00,20.0,186.00,78.00,2.34e+07,2.00,2.00,75.00,0.00,0.00,1.00,0.00,0.00,0.00,1.00,27.00,33.00,0.86,1.00,0.00,1.00,0.00,1.00,1.00,1.00,0.00,1.00,1.00,2.00,4.00,1.00,0.00,0.0,0.00e+00,0.00,0.00,0.00,0.00,0.00e+00,0.00,0.00e+00,7.90,0.90,32.70,20.00,17.00,90.00,6.40,64.10,60.80,71.30,4.00,75.10,59.00,78.90,63.90,1.00,1.00,359.00,0.00,6.40
max,39.00,26.0,200.00,87.00,2.00e+08,7.00,7.00,90.00,4.00,3.00,11.00,5.00,2.31,2.20,8.00,97.00,100.00,0.97,10.00,6.00,8.00,2.00,8.00,7.00,12.00,4.00,7.00,5.00,12.00,23.00,5.00,4.00,1.0,1.00e+00,4.00,11.00,1.00,3.00,1.00e+00,7.00,1.00e+00,14.00,2.00,37.00,44.00,40.00,99.00,9.40,97.70,99.00,99.00,37.00,99.00,99.00,99.00,99.00,10.00,8.00,615.00,4.00,9.50

In [37]:
df.loc[df['team'] == 'Japan']

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,club_name,market_value_eur,match_id,match_date,stadium,city,opponent_team,tournament_stage,match_result,goals_team,goals_opponent,minutes_played,goals,assists,shots,shots_on_target,expected_goals_xg,expected_assists_xa,key_passes,successful_passes,total_passes,pass_accuracy,dribbles_attempted,successful_dribbles,crosses,successful_crosses,tackles,interceptions,clearances,blocks,aerial_duels_won,aerial_duels_lost,recoveries,defensive_actions,fouls_committed,fouls_suffered,yellow_cards,red_cards,offsides,saves,save_percentage,punches,clean_sheet,goals_conceded,penalty_saves,distance_covered_km,sprint_distance_km,top_speed_kmh,accelerations,decelerations,stamina_score,player_rating,performance_score,offensive_contribution,defensive_contribution,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
1664,P00807,Daichi Kubo,24,Japanese,Japan,1,Goalkeeper,194,85,Right,Persepolis,16748378,M00033,2026-06-18,Estadio Azteca,Mexico City,Germany,Group Stage,D,0,0,54,0,0,0,0,0.0,0.00,0,8,10,0.80,0,0,0,0,0,1,0,0,0,0,2,1,1,1,0,0,0,1,0.66,0,0,0,0,5.2,0.7,31.0,17,12,97.3,5.9,58.9,9.8,70.9,1.8,66.2,46.8,58.9,53.0,0,0,147,0,5.8
1665,P00832,Junya Kamada,21,Japanese,Japan,26,Forward,179,71,Right,Melbourne City,7289620,M00033,2026-06-18,Estadio Azteca,Mexico City,Germany,Group Stage,D,0,0,76,0,0,1,0,0.0,0.00,0,15,21,0.73,0,0,0,0,1,0,0,0,4,1,2,1,1,1,0,0,1,0,0.00,0,0,0,0,8.3,0.8,33.1,24,17,63.9,5.6,56.2,26.6,21.5,1.3,50.5,33.9,39.6,58.1,2,0,369,0,5.4
1666,P00811,Takefusa Tanaka,18,Japanese,Japan,5,Defender,187,78,Right,Sydney FC,15931408,M00033,2026-06-18,Estadio Azteca,Mexico City,Germany,Group Stage,D,0,0,85,0,0,0,0,0.0,0.00,0,41,51,0.82,0,0,1,0,2,3,10,2,0,2,6,17,2,1,0,0,0,0,0.00,0,0,0,0,8.4,0.7,31.8,12,36,80.9,6.3,59.5,31.0,78.7,5.8,65.3,14.8,74.7,43.0,0,0,273,0,6.4
1667,P00816,Ao Mori,25,Japanese,Japan,10,Defender,184,72,Right,Melbourne City,2700538,M00033,2026-06-18,Estadio Azteca,Mexico City,Germany,Group Stage,D,0,0,90,0,0,1,0,0.0,0.00,0,33,39,0.86,1,0,4,1,4,3,9,1,1,2,2,17,0,0,0,0,0,0,0.00,0,0,0,0,8.8,1.0,28.6,12,25,67.6,6.5,61.8,22.9,56.7,2.7,37.3,27.3,45.0,52.7,0,1,490,0,6.4
1668,P00829,Kaoru Shiotani,29,Japanese,Japan,23,Forward,169,70,Right,Al-Ittihad,13869063,M00033,2026-06-18,Estadio Azteca,Mexico City,Germany,Group Stage,D,0,0,59,0,1,2,0,0.0,0.16,3,21,26,0.84,3,1,0,0,0,0,1,0,2,0,3,1,0,0,0,0,0,0,0.00,0,0,0,0,6.2,0.6,30.0,19,18,89.7,7.0,71.6,72.6,19.6,6.2,71.2,59.0,56.7,53.0,0,2,400,0,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51371,P00811,Takefusa Tanaka,18,Japanese,Japan,5,Defender,187,78,Right,Sydney FC,15931408,M00988,2026-07-22,Levi's Stadium,San Francisco,Morocco,Semi Finals,L,0,2,0,0,0,0,0,0.0,0.00,0,0,0,0.86,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,85.0,0.0,0.0,25.8,76.9,0.0,99.0,50.6,56.8,94.2,0,0,138,0,0.0
51372,P00814,Ritsu Ito,24,Japanese,Japan,8,Defender,183,81,Right,Esteghlal,4329214,M00988,2026-07-22,Levi's Stadium,San Francisco,Morocco,Semi Finals,L,0,2,0,0,0,0,0,0.0,0.00,0,0,0,0.75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,60.5,0.0,2.0,22.1,36.1,0.0,35.7,44.6,39.8,52.6,0,0,204,0,0.0
51373,P00822,Wataru Ueda,31,Japanese,Japan,16,Midfielder,180,77,Right,Kawasaki Frontale,15705102,M00988,2026-07-22,Levi's Stadium,San Francisco,Morocco,Semi Finals,L,0,2,0,0,0,0,0,0.0,0.00,0,0,0,0.85,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,78.8,0.0,1.3,51.3,57.8,0.0,65.0,59.9,68.7,49.5,2,0,421,0,0.0
51374,P00809,Kaoru Kamada,33,Japanese,Japan,3,Goalkeeper,191,80,Right,Yokohama F. Marinos,16497986,M00988,2026-07-22,Levi's Stadium,San Francisco,Morocco,Semi Finals,L,0,2,0,0,0,0,0,0.0,0.00,0,0,0,0.59,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,85.6,0.0,4.6,17.0,80.7,0.0,80.6,32.5,64.7,83.8,0,0,91,0,0.0
51375,P00808,Takefusa Endo,29,Japanese,Japan,2,Goalkeeper,189,80,Right,Kawasaki Frontale,1641172,M00988,2026-07-22,Levi's Stadium,San Francisco,Morocco,Semi Finals,L,0,2,0,0,0,0,0,0.0,0.00,0,0,0,0.75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,70.1,0.0,3.1,9.6,54.6,0.0,50.7,13.7,40.2,45.4,0,0,362,0,0.0